In [1]:
'''
Import the numpy package under the name np
'''
import numpy as np


In [9]:
'''Create a null vector of size 10 
'''
a = np.zeros([10])
print a

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [10]:
'''Create a null vector of size 10 but the fifth value which is 1
'''
a = np.zeros([10])
a[4] = 1
print a

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [15]:
'''Find indices of non-zero elements from [1,2,0,0,4,0]
'''
a = np.array([1,2,0,0,4,0])
print a[a >0]

[1 2 4]


In [19]:
'''Create a 10x10 array with random values and find the minimum and maximum values
'''
a = np.random.random([10,10])
print a
print a.max()
print a.min()

[[ 0.43205262  0.60452146  0.74160699  0.88218108  0.07839502  0.03836493
   0.82479819  0.61082974  0.52045643  0.53378047]
 [ 0.47380408  0.86850953  0.14853175  0.70000008  0.18477355  0.0384567
   0.63683925  0.41579134  0.23395784  0.34985309]
 [ 0.87921732  0.4653765   0.01780509  0.15506918  0.72537658  0.58974299
   0.16000485  0.4975352   0.83828424  0.59913148]
 [ 0.25578282  0.16383037  0.23736624  0.23632195  0.8985761   0.75940538
   0.77266745  0.38993181  0.04760279  0.5146151 ]
 [ 0.12744097  0.33759392  0.07012874  0.54032882  0.97343317  0.00929622
   0.49889678  0.6242482   0.10794637  0.02836888]
 [ 0.83608421  0.0953989   0.53225532  0.65227136  0.31085963  0.37455147
   0.01040423  0.27689589  0.59340321  0.60451644]
 [ 0.40794517  0.51181184  0.17051352  0.95692921  0.29738871  0.29451103
   0.11349622  0.16792856  0.98007161  0.07694616]
 [ 0.2834981   0.79280644  0.90489023  0.51763966  0.32886072  0.50041002
   0.07707419  0.35696817  0.90361757  0.87049556]
 

In [47]:
'''
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
'''
a = np.random.randint(10, size=(5,3))
print a
b = np.random.randint(5, size=(3,2))
print b

print a.dot(b)

[[1 2 2]
 [5 4 1]
 [5 7 5]
 [3 2 0]
 [7 1 5]]
[[3 1]
 [2 4]
 [0 0]]
[[ 7  9]
 [23 21]
 [29 33]
 [13 11]
 [23 11]]


In [52]:
'''
Create a random vector of size 10 and sort it

'''
a = np.random.randint(100, size=(10))
print np.sort(a)

[ 7  8 10 36 58 60 60 65 69 77]
